// <auto-generated />
using System;
using GymFitPlus.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymFitPlus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240402181927_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aea2775e-48f6-44ff-a3bd-219937657117"),
                            ConcurrencyStamp = "0fd4be9c-98aa-4750-8a67-0b8208bdd61d",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date")
                        .HasComment("User birth date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Link to user Facebook account");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("User first name");

                    b.Property<int?>("Gender")
                        .HasColumnType("int")
                        .HasComment("User gender");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)")
                        .HasComment("User profile image");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Link to user Instagram account");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("User last name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("YouTubeUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Link to user YouTube account");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasComment("Table with registered application users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(2003, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "a1015040-fe41-429a-9f8f-5bc39dcfe73e",
                            Email = "firstUser@mail.bg",
                            EmailConfirmed = false,
                            FacebookUrl = "https://www.facebook.com/Valkata13/",
                            FirstName = "Valentin",
                            Gender = 1,
                            InstagramUrl = "https://www.instagram.com/valkatasumaz/",
                            LastName = "Kirilov",
                            LockoutEnabled = false,
                            NormalizedEmail = "FIRSTUSER@MAIL.BG",
                            NormalizedUserName = "FIRSTUSER",
                            PasswordHash = "AQAAAAEAACcQAAAAEGvBl+0+8jLQB678Lt2YjCLaHoZ6i30xi4xdwgJX2bwKcmpgvZPXpl57l45yrIRmAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "de760688-941d-4354-9887-0d2baa9f0d7e",
                            TwoFactorEnabled = false,
                            UserName = "FirstUser",
                            YouTubeUrl = "https://www.youtube.com/channel/UCPntCGP5MhDGIvs4qtCmSeQ"
                        },
                        new
                        {
                            Id = new Guid("e3f4c702-f7bd-483e-8eb6-4bb91d0f0bb4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7853abb7-5df7-43af-8cb6-e4c7d038b507",
                            Email = "admin@mail.bg",
                            EmailConfirmed = false,
                            FirstName = "Admina",
                            LastName = "Ada",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.BG",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEA+/2NaBYiTwaySMNKi3qZ107gEtmq+qUkvhbKIxv5w+/AFvOF3mnVDP6NTJPqhBUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6e26d4b2-0084-45e8-9d5a-9224d80cd295",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Exercise identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasComment("Exercise description");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("Exercise status");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int")
                        .HasComment("Exercise muscle group target");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Exercise name");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Exercise video link");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasComment("Table of Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This exercise focuses on developing the upper portion of the chest muscles using dumbbells. It typically involves lying on a bench with dumbbells in hand, then pressing the weights upward in a controlled motion, targeting the upper chest area for strength and definition.",
                            IsDelete = false,
                            MuscleGroup = 1,
                            Name = "Dumbbell Upper Chest",
                            VideoUrl = "EFbifMHOXPc"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The hip thrust is a lower body strength exercise that primarily targets the glutes, but also engages the hamstrings and lower back. In this exercise, the individual lies on their back with knees bent and feet flat on the ground, while lifting their hips upward by driving through the heels.",
                            IsDelete = false,
                            MuscleGroup = 8,
                            Name = "Hip trust",
                            VideoUrl = "xDmFkJxPzeM"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The squat is a fundamental lower body exercise that targets multiple muscle groups, including the quadriceps, hamstrings, glutes, and lower back. It involves bending the knees and hips to lower the body down into a seated position and then pushing back up to a standing position.",
                            IsDelete = false,
                            MuscleGroup = 7,
                            Name = "Squat",
                            VideoUrl = "bEv6CCg2BC8"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Shoulder press is typically performed by sitting or standing with a barbell or dumbbells held at shoulder height. The weight is then pressed overhead until the arms are fully extended, and then lowered back down to shoulder height. This movement strengthens the shoulders, triceps, and upper chest while also improving shoulder stability and mobility.",
                            IsDelete = false,
                            MuscleGroup = 3,
                            Name = "Shoulder press",
                            VideoUrl = "_RlRDWO2jfg"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The Romanian deadlift is a weightlifting exercise focusing on the hamstrings, glutes, and lower back. It involves hinging at the hips with a slight knee bend while holding a barbell or dumbbells, then returning to a standing position. It improves hip hinge mechanics and strengthens the posterior chain.",
                            IsDelete = false,
                            MuscleGroup = 8,
                            Name = "Romanian deadlift",
                            VideoUrl = "_oyxCn2iSjU"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The Wide-grip pull-up is a bodyweight exercise where an individual grips a pull-up bar with hands placed wider than shoulder-width apart. From a hanging position, they pull themselves upward until their chin passes the bar, engaging the muscles of the upper back, shoulders, and arms.",
                            IsDelete = false,
                            MuscleGroup = 2,
                            Name = "Wide-grip pull-up",
                            VideoUrl = "Hdc7Mw6BIEE"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The Front Raise is a shoulder exercise where you hold a dumbbell or barbell in front of your body and lift your arm forward until it's level with your shoulder.",
                            IsDelete = false,
                            MuscleGroup = 3,
                            Name = "Front raise",
                            VideoUrl = "hRJ6tR5-if0"
                        });
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.FitnessProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Fitness program identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("Exercise status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Fitness program name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Fitness program creator/owner");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FitnessPrograms");

                    b.HasComment("Table with fitness programs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDelete = false,
                            Name = "Push",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 2,
                            IsDelete = false,
                            Name = "Pull",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 3,
                            IsDelete = false,
                            Name = "Legs",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        });
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.FitnessProgramExercise", b =>
                {
                    b.Property<int>("FitnessProgramId")
                        .HasColumnType("int")
                        .HasComment("Fitness program identifier");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasComment("Exercise identifier");

                    b.Property<DateTime>("DateOfUpdate")
                        .HasColumnType("date")
                        .HasComment("Date Of Update");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasComment("Fitness program order");

                    b.Property<int>("Reps")
                        .HasColumnType("int")
                        .HasComment("Reps for the exercise");

                    b.Property<int>("Sets")
                        .HasColumnType("int")
                        .HasComment("Sets for the exercise");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasComment("Weight for the exercise");

                    b.HasKey("FitnessProgramId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("FitnessProgramsExercises");

                    b.HasComment("Table of Exercise in one fitness program");

                    b.HasData(
                        new
                        {
                            FitnessProgramId = 1,
                            ExerciseId = 1,
                            DateOfUpdate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Order = 1,
                            Reps = 12,
                            Sets = 4,
                            Weight = 25.0
                        },
                        new
                        {
                            FitnessProgramId = 1,
                            ExerciseId = 4,
                            DateOfUpdate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Order = 2,
                            Reps = 12,
                            Sets = 4,
                            Weight = 40.0
                        },
                        new
                        {
                            FitnessProgramId = 1,
                            ExerciseId = 7,
                            DateOfUpdate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Order = 3,
                            Reps = 12,
                            Sets = 4,
                            Weight = 10.0
                        },
                        new
                        {
                            FitnessProgramId = 2,
                            ExerciseId = 5,
                            DateOfUpdate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Order = 1,
                            Reps = 12,
                            Sets = 4,
                            Weight = 75.0
                        },
                        new
                        {
                            FitnessProgramId = 2,
                            ExerciseId = 6,
                            DateOfUpdate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Order = 2,
                            Reps = 12,
                            Sets = 4,
                            Weight = 55.0
                        },
                        new
                        {
                            FitnessProgramId = 3,
                            ExerciseId = 2,
                            DateOfUpdate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Order = 1,
                            Reps = 12,
                            Sets = 4,
                            Weight = 100.0
                        },
                        new
                        {
                            FitnessProgramId = 3,
                            ExerciseId = 3,
                            DateOfUpdate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Order = 2,
                            Reps = 12,
                            Sets = 4,
                            Weight = 80.0
                        });
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Recipe identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("CaloriesPerHundredGrams")
                        .HasColumnType("float")
                        .HasComment("Calories in 100 grams of food");

                    b.Property<double>("CarbsPerHundredGrams")
                        .HasColumnType("float")
                        .HasComment("Carbohidrates in 100 grams of food");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasComment("Recipe category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Recipe description about needed products and way of cooking");

                    b.Property<double>("FatPerHundredGrams")
                        .HasColumnType("float")
                        .HasComment("Fat in 100 grams of food");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)")
                        .HasComment("Food image");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasComment("Recipe status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Recipe name");

                    b.Property<double>("ProteinPerHundredGrams")
                        .HasColumnType("float")
                        .HasComment("Protein in 100 grams of food");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasComment("Table of recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPerHundredGrams = 320.0,
                            CarbsPerHundredGrams = 4.2000000000000002,
                            Category = 1,
                            Description = "Ingredients: 3 eggs, 50g diced chicken breast, 30g spinach, 20g diced tomatoes, salt, pepper, 10g grated cheese (optional).Method: Beat eggs and season with salt and pepper. Cook chicken in a pan, add spinach and   tomatoes.Pour eggs over the mixture, cook until set. Add cheese if desired.",
                            FatPerHundredGrams = 24.300000000000001,
                            IsDelete = false,
                            Name = "Protein-Packed Omelette",
                            ProteinPerHundredGrams = 18.5
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPerHundredGrams = 280.0,
                            CarbsPerHundredGrams = 8.0,
                            Category = 1,
                            Description = "Ingredients: 150g grilled chicken breast, mixed salad greens (lettuce, spinach, arugula), 50g cherry   tomatoes, 30g cucumber, 20g feta cheese, 1 tbsp olive oil, balsamic vinegar. Method: Grill chicken, cho into     pieces.Toss with salad greens, tomatoes, cucumber, and crumbled feta. Drizzle with olive oil an balsamic     vinegar.",
                            FatPerHundredGrams = 15.0,
                            IsDelete = false,
                            Name = "Grilled Chicken Salad",
                            ProteinPerHundredGrams = 26.0
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPerHundredGrams = 320.0,
                            CarbsPerHundredGrams = 33.0,
                            Category = 1,
                            Description = "Ingredients: 100g canned tuna, 100g cooked quinoa, 50g diced bell peppers, 30g diced onions, 20g chopped parsley, 1 tbsp lemon juice, salt, pepper. Method: Mix tuna, quinoa, bell peppers, onions, and parsley. Season with lemon juice, salt, and pepper. Serve chilled.",
                            FatPerHundredGrams = 10.0,
                            IsDelete = false,
                            Name = "Tuna Quinoa Bowl",
                            ProteinPerHundredGrams = 21.0
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPerHundredGrams = 250.0,
                            CarbsPerHundredGrams = 30.0,
                            Category = 1,
                            Description = "Ingredients: 150g Greek yogurt, 50g mixed berries, 30g granola, honey (optional). Method: Layer Greek yogurt, berries, and granola in a glass. Drizzle with honey if desired. Repeat layers. Serve chilled.",
                            FatPerHundredGrams = 10.0,
                            IsDelete = false,
                            Name = "Greek Yogurt Parfait",
                            ProteinPerHundredGrams = 10.0
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPerHundredGrams = 280.0,
                            CarbsPerHundredGrams = 25.0,
                            Category = 2,
                            Description = "Ingredients: 2 scoops protein powder, 2 eggs, 50ml milk, 30g oat flour, 1 tsp baking powder, 1 tsp vanilla extract.Method: Mix all ingredients until smooth. Cook pancakes on a hot griddle until golden brown on both sides.Serve with toppings of choice.",
                            FatPerHundredGrams = 8.0,
                            IsDelete = false,
                            Name = "Protein Pancakes",
                            ProteinPerHundredGrams = 20.0
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPerHundredGrams = 300.0,
                            CarbsPerHundredGrams = 5.0,
                            Category = 1,
                            Description = "Ingredients: 150g salmon fillet, 100g asparagus spears, 1 tbsp olive oil, lemon wedges, salt, pepper.    Method: Season salmon with salt and pepper.Grill or bake until cooked through. Sauté asparagus in olive oil    until tender.Serve salmon with asparagus, garnish with lemon wedges.",
                            FatPerHundredGrams = 18.0,
                            IsDelete = false,
                            Name = "Salmon with Asparagus",
                            ProteinPerHundredGrams = 24.0
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPerHundredGrams = 220.0,
                            CarbsPerHundredGrams = 25.0,
                            Category = 2,
                            Description = "Ingredients: 1 scoop protein powder, 150ml almond milk, 1 banana, 50g spinach, 30g oats, 5g almond butter, ice cubes.Method: Blend all ingredients until smooth. Adjust consistency with more milk if needed.Enjoy immediately.",
                            FatPerHundredGrams = 5.0,
                            IsDelete = false,
                            Name = "Protein-Packed Smoothie",
                            ProteinPerHundredGrams = 10.0
                        });
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.UserRecipe", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("User identifier");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasComment("Recipe identifier");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("User note to current recipe");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UsersRecipes");

                    b.HasComment("Table of users and recipes");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            RecipeId = 3,
                            Note = "Need more protein"
                        },
                        new
                        {
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            RecipeId = 4
                        },
                        new
                        {
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            RecipeId = 5,
                            Note = "Add some sugar"
                        },
                        new
                        {
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            RecipeId = 1
                        });
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.UserStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Statistics identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("BackCircumference")
                        .HasColumnType("float")
                        .HasComment("Back circumference of user in centimeters");

                    b.Property<double>("ChestCircumference")
                        .HasColumnType("float")
                        .HasComment("Chest circumference of user in centimeters");

                    b.Property<DateTime>("DateOfМeasurements")
                        .HasColumnType("date")
                        .HasComment("Date Of Мeasurements");

                    b.Property<double>("GluteusCircumference")
                        .HasColumnType("float")
                        .HasComment("Gluteus circumference of user in centimeters");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasComment("Height of user in meters");

                    b.Property<double>("LeftArmCircumference")
                        .HasColumnType("float")
                        .HasComment("Left arm circumference of user in centimeters");

                    b.Property<double>("LeftCalfCircumference")
                        .HasColumnType("float")
                        .HasComment("Left calf circumference of user in centimeters");

                    b.Property<double>("LeftLegCircumference")
                        .HasColumnType("float")
                        .HasComment("Left leg circumference of user in centimeters");

                    b.Property<double>("RightArmCircumference")
                        .HasColumnType("float")
                        .HasComment("Right arm circumference of user in centimeters");

                    b.Property<double>("RightCalfCircumference")
                        .HasColumnType("float")
                        .HasComment("Right calf circumference of user in centimeters");

                    b.Property<double>("RightLegCircumference")
                        .HasColumnType("float")
                        .HasComment("Right leg circumference of user in centimeters");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Statistics owner");

                    b.Property<double>("WaistCircumference")
                        .HasColumnType("float")
                        .HasComment("Waist circumference of user in centimeters");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasComment("Weight of user in kilograms");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserStatistics");

                    b.HasComment("Table with statistics of users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackCircumference = 150.0,
                            ChestCircumference = 110.0,
                            DateOfМeasurements = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GluteusCircumference = 50.0,
                            Height = 174.0,
                            LeftArmCircumference = 43.0,
                            LeftCalfCircumference = 35.399999999999999,
                            LeftLegCircumference = 80.599999999999994,
                            RightArmCircumference = 43.299999999999997,
                            RightCalfCircumference = 35.299999999999997,
                            RightLegCircumference = 80.0,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            WaistCircumference = 40.0,
                            Weight = 75.200000000000003
                        },
                        new
                        {
                            Id = 2,
                            BackCircumference = 151.0,
                            ChestCircumference = 112.0,
                            DateOfМeasurements = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GluteusCircumference = 51.0,
                            Height = 175.0,
                            LeftArmCircumference = 43.5,
                            LeftCalfCircumference = 35.600000000000001,
                            LeftLegCircumference = 81.200000000000003,
                            RightArmCircumference = 43.799999999999997,
                            RightCalfCircumference = 35.5,
                            RightLegCircumference = 81.0,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            WaistCircumference = 41.0,
                            Weight = 76.5
                        },
                        new
                        {
                            Id = 3,
                            BackCircumference = 149.0,
                            ChestCircumference = 111.0,
                            DateOfМeasurements = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GluteusCircumference = 50.5,
                            Height = 173.0,
                            LeftArmCircumference = 43.200000000000003,
                            LeftCalfCircumference = 35.5,
                            LeftLegCircumference = 80.799999999999997,
                            RightArmCircumference = 43.5,
                            RightCalfCircumference = 35.399999999999999,
                            RightLegCircumference = 80.5,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            WaistCircumference = 40.5,
                            Weight = 75.799999999999997
                        },
                        new
                        {
                            Id = 4,
                            BackCircumference = 148.0,
                            ChestCircumference = 109.0,
                            DateOfМeasurements = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GluteusCircumference = 50.0,
                            Height = 172.0,
                            LeftArmCircumference = 42.799999999999997,
                            LeftCalfCircumference = 35.299999999999997,
                            LeftLegCircumference = 80.400000000000006,
                            RightArmCircumference = 43.100000000000001,
                            RightCalfCircumference = 35.200000000000003,
                            RightLegCircumference = 80.0,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            WaistCircumference = 40.0,
                            Weight = 75.0
                        },
                        new
                        {
                            Id = 5,
                            BackCircumference = 147.0,
                            ChestCircumference = 108.0,
                            DateOfМeasurements = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GluteusCircumference = 49.5,
                            Height = 171.0,
                            LeftArmCircumference = 42.600000000000001,
                            LeftCalfCircumference = 35.200000000000003,
                            LeftLegCircumference = 80.0,
                            RightArmCircumference = 42.899999999999999,
                            RightCalfCircumference = 35.100000000000001,
                            RightLegCircumference = 79.5,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            WaistCircumference = 39.5,
                            Weight = 74.700000000000003
                        },
                        new
                        {
                            Id = 6,
                            BackCircumference = 146.0,
                            ChestCircumference = 107.0,
                            DateOfМeasurements = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GluteusCircumference = 49.0,
                            Height = 170.0,
                            LeftArmCircumference = 42.399999999999999,
                            LeftCalfCircumference = 35.100000000000001,
                            LeftLegCircumference = 79.599999999999994,
                            RightArmCircumference = 42.700000000000003,
                            RightCalfCircumference = 35.0,
                            RightLegCircumference = 79.0,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            WaistCircumference = 39.0,
                            Weight = 74.5
                        },
                        new
                        {
                            Id = 7,
                            BackCircumference = 145.0,
                            ChestCircumference = 106.0,
                            DateOfМeasurements = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GluteusCircumference = 48.5,
                            Height = 169.0,
                            LeftArmCircumference = 42.200000000000003,
                            LeftCalfCircumference = 35.0,
                            LeftLegCircumference = 79.0,
                            RightArmCircumference = 42.5,
                            RightCalfCircumference = 34.899999999999999,
                            RightLegCircumference = 78.5,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            WaistCircumference = 38.5,
                            Weight = 74.200000000000003
                        },
                        new
                        {
                            Id = 8,
                            BackCircumference = 144.0,
                            ChestCircumference = 105.0,
                            DateOfМeasurements = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GluteusCircumference = 48.0,
                            Height = 168.0,
                            LeftArmCircumference = 42.0,
                            LeftCalfCircumference = 34.899999999999999,
                            LeftLegCircumference = 78.400000000000006,
                            RightArmCircumference = 42.299999999999997,
                            RightCalfCircumference = 34.799999999999997,
                            RightLegCircumference = 78.0,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6"),
                            WaistCircumference = 38.0,
                            Weight = 74.0
                        });
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Workout identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasComment("Date of workout");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration of workout in minutes");

                    b.Property<int>("FitnessProgramId")
                        .HasColumnType("int")
                        .HasComment("Fitness program that is used in workout");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("User note on workout");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Workout owner");

                    b.HasKey("Id");

                    b.HasIndex("FitnessProgramId");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");

                    b.HasComment("Table with users workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 120,
                            FitnessProgramId = 1,
                            Note = "Need more pump in chests",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 90,
                            FitnessProgramId = 1,
                            Note = "Focused on cardio",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 60,
                            FitnessProgramId = 2,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 75,
                            FitnessProgramId = 3,
                            Note = "Increased weight in squats",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 105,
                            FitnessProgramId = 1,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 45,
                            FitnessProgramId = 2,
                            Note = "Focused on core exercises",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 80,
                            FitnessProgramId = 3,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 110,
                            FitnessProgramId = 1,
                            Note = "Feeling energetic today",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 50,
                            FitnessProgramId = 2,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 70,
                            FitnessProgramId = 3,
                            Note = "Need to work on flexibility",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 100,
                            FitnessProgramId = 1,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2024, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 55,
                            FitnessProgramId = 2,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 85,
                            FitnessProgramId = 3,
                            Note = "Focused on upper body",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 95,
                            FitnessProgramId = 1,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 40,
                            FitnessProgramId = 2,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 65,
                            FitnessProgramId = 3,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 120,
                            FitnessProgramId = 1,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 60,
                            FitnessProgramId = 2,
                            Note = "Need to increase intensity",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 75,
                            FitnessProgramId = 3,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 105,
                            FitnessProgramId = 1,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 45,
                            FitnessProgramId = 2,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 80,
                            FitnessProgramId = 3,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 110,
                            FitnessProgramId = 1,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 50,
                            FitnessProgramId = 2,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 70,
                            FitnessProgramId = 3,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 120,
                            FitnessProgramId = 1,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 55,
                            FitnessProgramId = 2,
                            Note = "Feeling motivated today",
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 85,
                            FitnessProgramId = 3,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2024, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 95,
                            FitnessProgramId = 1,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 40,
                            FitnessProgramId = 2,
                            UserId = new Guid("4a2d18dc-e328-4940-807f-85b8ac83afc6")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e3f4c702-f7bd-483e-8eb6-4bb91d0f0bb4"),
                            RoleId = new Guid("aea2775e-48f6-44ff-a3bd-219937657117")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.FitnessProgram", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany("FitnessPrograms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.FitnessProgramExercise", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.Exercise", "Exercise")
                        .WithMany("FitnessProgramsExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.FitnessProgram", "FitnessProgram")
                        .WithMany("FitnessProgramsExercises")
                        .HasForeignKey("FitnessProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("FitnessProgram");
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.UserRecipe", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.Recipe", "Recipe")
                        .WithMany("UsersRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany("UsersRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.UserStatistics", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany("UserStatistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.Workout", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.FitnessProgram", "FitnessProgram")
                        .WithMany("Workouts")
                        .HasForeignKey("FitnessProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FitnessProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("FitnessPrograms");

                    b.Navigation("UserStatistics");

                    b.Navigation("UsersRecipes");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.Exercise", b =>
                {
                    b.Navigation("FitnessProgramsExercises");
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.FitnessProgram", b =>
                {
                    b.Navigation("FitnessProgramsExercises");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GymFitPlus.Infrastructure.Data.Models.Recipe", b =>
                {
                    b.Navigation("UsersRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
